//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 11:41:17 PM EET 
//


package com.oyak.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClubKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClubKindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Driver"/>
 *     &lt;enumeration value="Wood"/>
 *     &lt;enumeration value="Iron"/>
 *     &lt;enumeration value="Wedge"/>
 *     &lt;enumeration value="Putter"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ClubKindType")
@XmlEnum
public enum ClubKindType {

    @XmlEnumValue("Driver")
    DRIVER("Driver"),
    @XmlEnumValue("Wood")
    WOOD("Wood"),
    @XmlEnumValue("Iron")
    IRON("Iron"),
    @XmlEnumValue("Wedge")
    WEDGE("Wedge"),
    @XmlEnumValue("Putter")
    PUTTER("Putter");
    private final String value;

    ClubKindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClubKindType fromValue(String v) {
        for (ClubKindType c: ClubKindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
