//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 11:41:17 PM EET 
//


package com.oyak.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExclusiveMemberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExclusiveMemberType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/GolfCountryClub}PersonType">
 *       &lt;sequence>
 *         &lt;element name="ValetParkingID" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="LockerNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExclusiveMemberType", propOrder = {
    "valetParkingID",
    "lockerNumber"
})
public class ExclusiveMemberType
    extends PersonType
{

    @XmlElement(name = "ValetParkingID", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger valetParkingID;
    @XmlElement(name = "LockerNumber", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lockerNumber;

    /**
     * Gets the value of the valetParkingID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getValetParkingID() {
        return valetParkingID;
    }

    /**
     * Sets the value of the valetParkingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setValetParkingID(BigInteger value) {
        this.valetParkingID = value;
    }

    /**
     * Gets the value of the lockerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLockerNumber() {
        return lockerNumber;
    }

    /**
     * Sets the value of the lockerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLockerNumber(BigInteger value) {
        this.lockerNumber = value;
    }

}
