//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 11:41:17 PM EET 
//


package com.oyak.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GolfClubType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GolfClubType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/GolfCountryClub}GolfManufacturerType">
 *       &lt;sequence>
 *         &lt;element name="ClubKind" type="{http://www.example.org/GolfCountryClub}ClubKindType"/>
 *         &lt;element name="Loft" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Shaft" type="{http://www.example.org/GolfCountryClub}ShaftType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GolfClubType", propOrder = {
    "clubKind",
    "loft",
    "shaft"
})
public class GolfClubType
    extends GolfManufacturerType
{

    @XmlElement(name = "ClubKind", required = true)
    @XmlSchemaType(name = "string")
    protected ClubKindType clubKind;
    @XmlElement(name = "Loft", required = true)
    protected String loft;
    @XmlElement(name = "Shaft", required = true)
    @XmlSchemaType(name = "string")
    protected ShaftType shaft;

    /**
     * Gets the value of the clubKind property.
     * 
     * @return
     *     possible object is
     *     {@link ClubKindType }
     *     
     */
    public ClubKindType getClubKind() {
        return clubKind;
    }

    /**
     * Sets the value of the clubKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClubKindType }
     *     
     */
    public void setClubKind(ClubKindType value) {
        this.clubKind = value;
    }

    /**
     * Gets the value of the loft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoft() {
        return loft;
    }

    /**
     * Sets the value of the loft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoft(String value) {
        this.loft = value;
    }

    /**
     * Gets the value of the shaft property.
     * 
     * @return
     *     possible object is
     *     {@link ShaftType }
     *     
     */
    public ShaftType getShaft() {
        return shaft;
    }

    /**
     * Sets the value of the shaft property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShaftType }
     *     
     */
    public void setShaft(ShaftType value) {
        this.shaft = value;
    }

}
