//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 11:41:17 PM EET 
//


package com.oyak.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LimitedPlayType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LimitedPlayType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Weekday Only"/>
 *     &lt;enumeration value="Weekend Only"/>
 *     &lt;enumeration value="Anytime after twilight"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LimitedPlayType")
@XmlEnum
public enum LimitedPlayType {

    @XmlEnumValue("Weekday Only")
    WEEKDAY_ONLY("Weekday Only"),
    @XmlEnumValue("Weekend Only")
    WEEKEND_ONLY("Weekend Only"),
    @XmlEnumValue("Anytime after twilight")
    ANYTIME_AFTER_TWILIGHT("Anytime after twilight");
    private final String value;

    LimitedPlayType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LimitedPlayType fromValue(String v) {
        for (LimitedPlayType c: LimitedPlayType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
