//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 11:41:17 PM EET 
//


package com.oyak.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oyak.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GolfClub_QNAME = new QName("http://www.example.org/GolfCountryClub", "GolfClub");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oyak.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GolfCountryClub }
     * 
     */
    public GolfCountryClub createGolfCountryClub() {
        return new GolfCountryClub();
    }

    /**
     * Create an instance of {@link GolfClubType }
     * 
     */
    public GolfClubType createGolfClubType() {
        return new GolfClubType();
    }

    /**
     * Create an instance of {@link GolfCourseType }
     * 
     */
    public GolfCourseType createGolfCourseType() {
        return new GolfCourseType();
    }

    /**
     * Create an instance of {@link GolfCountryClub.Member }
     * 
     */
    public GolfCountryClub.Member createGolfCountryClubMember() {
        return new GolfCountryClub.Member();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public EmployeeType createEmployeeType() {
        return new EmployeeType();
    }

    /**
     * Create an instance of {@link GolfCountryClub.ProShop }
     * 
     */
    public GolfCountryClub.ProShop createGolfCountryClubProShop() {
        return new GolfCountryClub.ProShop();
    }

    /**
     * Create an instance of {@link GolfManufacturerType }
     * 
     */
    public GolfManufacturerType createGolfManufacturerType() {
        return new GolfManufacturerType();
    }

    /**
     * Create an instance of {@link BoxOfBallsType }
     * 
     */
    public BoxOfBallsType createBoxOfBallsType() {
        return new BoxOfBallsType();
    }

    /**
     * Create an instance of {@link RegularMemberType }
     * 
     */
    public RegularMemberType createRegularMemberType() {
        return new RegularMemberType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link RestrictedMemberType }
     * 
     */
    public RestrictedMemberType createRestrictedMemberType() {
        return new RestrictedMemberType();
    }

    /**
     * Create an instance of {@link ExclusiveMemberType }
     * 
     */
    public ExclusiveMemberType createExclusiveMemberType() {
        return new ExclusiveMemberType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GolfClubType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/GolfCountryClub", name = "GolfClub")
    public JAXBElement<GolfClubType> createGolfClub(GolfClubType value) {
        return new JAXBElement<GolfClubType>(_GolfClub_QNAME, GolfClubType.class, null, value);
    }

}
